<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.10.3 setup script
 * Date: Tue, 18 Aug 2015 15:39:45 +0100
 */

/* Servers configuration */
$i = 0;

/**
 * First server
 */
$i++;
/* Authentication type */
$cfg['Servers'][$i]['auth_type'] = 'cookie';
/* Server parameters */
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* Server: moodle-dev.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle-dev.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3304';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'mdluser_dev';
$cfg['Servers'][$i]['password'] = 'Mdl@dev1';

/* Server: moodle-uat.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle-uat.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3305';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'mdluser_uat';
$cfg['Servers'][$i]['password'] = 'Mdl@uat1';

/* Server: moodle-db-pp.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle-db-pp.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3307';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'moodleuser';
$cfg['Servers'][$i]['password'] = 'kw+2_nE,';

/* Server: moodle-db-a.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle-db-a.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3308';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'moodleuser';
$cfg['Servers'][$i]['password'] = 'kw+2_nE,';

/* Server: moodle-db-a.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle_sits_management_2 - moodle-db-a';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3309';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'sitsfilteruserp';
$cfg['Servers'][$i]['password'] = 'TlTKaTC0cdnsUwPE9pL8';

/* Server: moodle-db-b.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle-db-b.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3310';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'moodleuser';
$cfg['Servers'][$i]['password'] = 'kw+2_nE,';

/* Server: moodle-db-b.ucl.ac.uk - sits */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle-db-b - moodle_sits_management_2';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3311';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'sitsfilteruserp';
$cfg['Servers'][$i]['password'] = 'TlTKaTC0cdnsUwPE9pL8';

/* Server: moodle-snapshot-a.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle-snapshot-a.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3312';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
//$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'moodleuser';
$cfg['Servers'][$i]['password'] = 'kw+2_nE,';

/* Server: moodle-test.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'moodle-test.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3313';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'mdluser_test';
$cfg['Servers'][$i]['password'] = 'Mdl@tst1';

/* Server: webapps-db-a.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'WordPress. webapps-db-a.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3314';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'wpmu_user';
$cfg['Servers'][$i]['password'] = '4blg;wpmuklb';

/* Server: webapps-dev.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mahara DEV. webapps-dev.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3315';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'mahara';
$cfg['Servers'][$i]['password'] = 'wMXlZbznTukQ';

/* Server: webapps-uat.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mahara UAT. webapps-uat.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3316';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'mahara';
$cfg['Servers'][$i]['password'] = 'wMXlZbznTukQ';

/* Server: webapps-db.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mahara PROD. webapps-db.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3317';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'mahara';
$cfg['Servers'][$i]['password'] = 'wMXlZbznTukQ';

/* Server: webapps-db.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'opinio PROD. webapps-db.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3318';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'opinio';
$cfg['Servers'][$i]['password'] = 'tr,6_cCt';

/* Server: webapps-db.ucl.ac.uk */
$i++;
$cfg['Servers'][$i]['verbose'] = 'wiki PROD. webapps-db.ucl.ac.uk';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3319';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'confluenceuser';
$cfg['Servers'][$i]['password'] = 'wikido11';

/* Allow to type any host*/
//$cfg['AllowArbitraryServer'] = true;

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '55d3417c3a4410.86631925';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
