
Notice: Undefined property: stdClass::$session_handler_class in /data/apache/moodle-vhosts/v31-0802/config.php on line 94

Notice: Undefined property: stdClass::$session_memcached_save_path in /data/apache/moodle-vhosts/v31-0802/config.php on line 95

Notice: Undefined property: stdClass::$session_memcached_prefix in /data/apache/moodle-vhosts/v31-0802/config.php on line 96

Notice: Undefined property: stdClass::$session_memcached_acquire_lock_timeout in /data/apache/moodle-vhosts/v31-0802/config.php on line 97

Notice: Undefined property: stdClass::$session_memcached_lock_expire in /data/apache/moodle-vhosts/v31-0802/config.php on line 98

Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /data/apache/moodle-vhosts/v31-0802/lib/classes/session/manager.php on line 475
stdClass Object
(
    [locale] => en
    [version] => 2016052300.02
    [release] => 3.1+ (Build: 20160603)
    [allowcoursethemes] => 0
    [allowemailaddresses] => 
    [allowobjectembed] => 0
    [allowunenroll] => 1
    [allowuserthemes] => 0
    [allowuserblockhiding] => 1
    [allusersaresitestudents] => 1
    [alternateloginurl] => 
    [aspellpath] => 
    [auth] => ldap,mnet,webservice
    [autologinguests] => 0
    [changepassword] => 
    [country] => GB
    [dbsessions] => 0
    [deleteunconfirmed] => 168
    [denyemailaddresses] => 
    [digestmailtime] => 17
    [displayloginfailures] => 0
    [enablerssfeeds] => 1
    [extendedusernamechars] => 1
    [filterall] => 0
    [filteruploadedfiles] => 2
    [forcelogin] => 0
    [forceloginforprofiles] => 1
    [forcetimezone] => 99
    [fullnamedisplay] => firstname lastname
    [frontpage] => 
    [gdversion] => 2
    [guestloginbutton] => 1
    [langcache] => 1
    [langmenu] => 0
    [langlist] => 
    [loginhttps] => 1
    [loglifetime] => 365
    [maxbytes] => 0
    [maxeditingtime] => 1800
    [messaging] => 1
    [noreplyaddress] => noreply@moodle.ucl.ac.uk
    [notifyloginfailures] => $@NONE@$
    [notifyloginthreshold] => 10
    [opentogoogle] => 0
    [pathtodu] => /usr/bin/du
    [proxyhost] => 
    [proxyport] => 
    [sessiontimeout] => 10800
    [showblocksonmodpages] => 0
    [sitepolicy] => https://moodle.ucl.ac.uk/pluginfile.php/1/theme_ucl/usepolicy/1442233325/UCL_Moodle_usage_policy.html
    [slasharguments] => 1
    [smtphosts] => 
    [smtppass] => 
    [smtpuser] => 
    [style] => default
    [teacherassignteachers] => 1
    [template] => default
    [themelist] => UCL
    [lang] => en
    [sessioncookie] => uclmoodle2
    [debug] => 15
    [perfdebug] => 7
    [sesskey] => ZJtrLLWobL
    [assignment_maxbytes] => 20971520
    [chat_refresh_room] => 5
    [chat_refresh_userlist] => 10
    [chat_old_ping] => 35
    [chat_method] => header_js
    [chat_serverhost] => moodlevm-a.ucl.ac.uk
    [chat_serverip] => 127.0.0.1
    [chat_serverport] => 9111
    [chat_servermax] => 100
    [forum_displaymode] => 3
    [forum_shortpost] => 300
    [forum_longpost] => 600
    [forum_manydiscussions] => 100
    [forum_maxbytes] => 2097152
    [forum_trackreadposts] => 1
    [forum_oldpostdays] => 31
    [forum_usermarksread] => 0
    [forum_cleanreadtime] => 2
    [forum_replytouser] => 1
    [glossary_studentspost] => 1
    [glossary_dupentries] => 0
    [glossary_allowcomments] => 0
    [glossary_linkbydefault] => 1
    [glossary_defaultapproval] => 1
    [glossary_entbypage] => 10
    [resource_filterexternalpages] => 0
    [resource_windowsettings] => 0
    [resource_parametersettings] => 0
    [backup_version] => 2016052300
    [backup_release] => 3.1
    [blocks_version] => 2007081300
    [auth_instructions] => 
    [auth_user_create] => 0
    [theme] => ucl
    [enrol_imsfilelocation] => /moodlefs/sits/sits_output.xml
    [enrol_logtolocation] => /var/log/ims_enterprise_log.txt
    [enrol_fixcaseusernames] => 1
    [enrol_fixcasepersonalnames] => 1
    [enrol_truncatecoursecodes] => 0
    [enrol_createnewcourses] => 1
    [enrol_createnewcategories] => 
    [enrol_createnewusers] => 1
    [enrol_imsdeleteusers] => 
    [enrol_mailadmins] => 
    [enrol_imsunenrol] => 
    [enrol_allowinternal] => 1
    [enrol_imssourcedidfallback] => 
    [enrol_imscapitafix] => 
    [enrol_processphoto] => 
    [enrol_imsrestricttarget] => 
    [enrol_ims_prev_time] => 1339724184
    [enrol_ims_prev_md5] => cecfc7c4390b4cd1c595f4fea9d14233
    [enrol_ims_prev_path] => /moodlefs/sits/sits_output.xml
    [digestmailtimelast] => 1470067841
    [forum_lastreadclean] => 1479998258
    [forum_enablerssfeeds] => 1
    [enrol_plugins_enabled] => manual,self,cohort,meta,category,guest,imsenterprise,dbuserrel
    [allowusermailcharset] => 0
    [bloglevel] => 4
    [defaultrequestedcategory] => 1
    [docroot] => http://docs.moodle.org
    [enablecourserequests] => 0
    [filtermatchoneperpage] => 0
    [filtermatchonepertext] => 0
    [mymoodleredirect] => 0
    [sessioncookiepath] => /
    [sitemailcharset] => 0
    [tinymceplugins] => advimage,fullscreen
    [tinymcetheme] => advanced
    [tinymcecontentcss] => http://moodle.ucl.ac.uk/lib/editor/tinymce/moodlecontent.css
    [tinymcepopupcss] => 
    [tinymceeditorcss] => 
    [filter_mediaplugin_enable_mov] => 1
    [filter_mediaplugin_enable_mpg] => 1
    [filter_mediaplugin_enable_wmv] => 1
    [filter_mediaplugin_enable_avi] => 1
    [filter_mediaplugin_enable_ram] => 1
    [filter_mediaplugin_enable_rpm] => 1
    [assignment_itemstocount] => 1
    [chat_normal_updatemode] => jsupdate
    [attemptuniqueid] => 213
    [resource_hide_repository] => 1
    [hiddenuserfields] => firstaccess
    [submit] => Save changes
    [calendar_adminseesall] => 0
    [calendar_startwday] => 1
    [calendar_weekend] => 65
    [calendar_lookahead] => 60
    [calendar_maxevents] => 10
    [glossary_enablerssfeeds] => 1
    [glossary_linkentries] => 0
    [glossary_casesensitive] => 0
    [glossary_fullmatch] => 0
    [data_enablerssfeeds] => 1
    [resource_autofilerename] => 1
    [resource_blockdeletingfile] => 1
    [rolesactive] => 1
    [notloggedinroleid] => 6
    [defaultuserroleid] => 28
    [defaultrequestcategory] => 1
    [protectusernames] => 1
    [enabletrusttext] => 0
    [coursesperpage] => 25
    [doctonewwindow] => 1
    [gradebookroles] => 5,26
    [enableajax] => 1
    [frontpageloggedin] => 
    [block_course_list_adminview] => own
    [filter_censor_badwords] => 
    [enrol_imse_imsrolemap01] => 5
    [enrol_imse_imsrolemap02] => 3
    [enrol_imse_imsrolemap03] => 3
    [enrol_imse_imsrolemap04] => 5
    [enrol_imse_imsrolemap05] => 1
    [enrol_imse_imsrolemap06] => 4
    [enrol_imse_imsrolemap07] => 1
    [enrol_imse_imsrolemap08] => 4
    [registerauth] => 
    [mnet_dispatcher_mode] => strict
    [mnet_localhost_id] => 1
    [mnet_all_hosts_id] => 2
    [guestroleid] => 6
    [creatornewroleid] => 3
    [latinexcelexport] => 0
    [cronclionly] => 0
    [cronremotepassword] => passw0rd
    [calendar_site_timeformat] => 0
    [debugdisplay] => 0
    [debugsmtp] => 0
    [smartpix] => 0
    [filter_multilang_converted] => 1
    [scorm_updatetimelast] => 1479996590
    [enablestats] => 0
    [statsfirstrun] => 604800
    [statsmaxruntime] => 0
    [statsruntimestarthour] => 1
    [statsruntimestartminute] => 5
    [statsuserthreshold] => 0
    [statslastdaily] => 1233705600
    [forgottenpasswordurl] => https://myaccount.ucl.ac.uk/
    [nodefaultuserrolelists] => 0
    [enableoutcomes] => 1
    [grade_profilereport] => user
    [grade_aggregationposition] => 1
    [grade_includescalesinaggregation] => 1
    [grade_hiddenasdate] => 0
    [gradepublishing] => 0
    [grade_export_displaytype] => 1
    [grade_export_decimalpoints] => 2
    [gradeexport] => 
    [grade_hideforcedsettings] => 1
    [grade_aggregation] => 11
    [grade_aggregation_flag] => 0
    [grade_aggregateonlygraded] => 1
    [grade_aggregateonlygraded_flag] => 2
    [grade_aggregateoutcomes] => 0
    [grade_aggregateoutcomes_flag] => 2
    [grade_aggregatesubcats] => 0
    [grade_aggregatesubcats_flag] => 2
    [grade_keephigh] => 0
    [grade_keephigh_flag] => 3
    [grade_droplow] => 0
    [grade_droplow_flag] => 2
    [grade_displaytype] => 1
    [grade_decimalpoints] => 2
    [grade_item_advanced] => iteminfo,idnumber,gradepass,plusfactor,multfactor,display,decimals,hiddenuntil,locktime
    [grade_report_studentsperpage] => 100
    [grade_report_quickgrading] => 1
    [grade_report_showquickfeedback] => 0
    [grade_report_aggregationview] => 0
    [grade_report_meanselection] => 1
    [grade_report_showcalculations] => 1
    [grade_report_showeyecons] => 1
    [grade_report_showaverages] => 1
    [grade_report_showlocks] => 0
    [grade_report_showranges] => 0
    [grade_report_showuserimage] => 1
    [grade_report_showactivityicons] => 1
    [grade_report_shownumberofgrades] => 0
    [grade_report_averagesdisplaytype] => inherit
    [grade_report_rangesdisplaytype] => inherit
    [grade_report_averagesdecimalpoints] => inherit
    [grade_report_rangesdecimalpoints] => inherit
    [grade_report_overview_showrank] => 0
    [grade_report_user_showrank] => 0
    [grade_report_user_showhiddenitems] => 1
    [geoipfile] => /data/moodle/geoip/GeoLiteCity.dat
    [autolang] => 1
    [assignment_showrecentsubmissions] => 1
    [forum_enabletimedposts] => 0
    [lams_serverurl] => 
    [lams_serverid] => 
    [lams_serverkey] => 
    [block_course_list_hideallcourseslink] => 0
    [block_online_users_timetosee] => 5
    [filter_multilang_force_old] => 0
    [usetags] => 1
    [keeptagnamecase] => 1
    [minpasswordlength] => 7
    [minpassworddigits] => 1
    [minpasswordlower] => 1
    [minpasswordupper] => 1
    [minpasswordnonalphanum] => 1
    [disableuserimages] => 0
    [allowcategorythemes] => 0
    [hideactivitytypenavlink] => 0
    [defaultfrontpageroleid] => 0
    [smtpmaxbulk] => 1
    [mailnewline] => LF
    [supportname] => E-Learning Environments
    [supportemail] => ccaalts@ucl.ac.uk
    [supportpage] => 
    [proxytype] => HTTP
    [proxyuser] => 
    [proxypassword] => 
    [disablegradehistory] => 0
    [gradehistorylifetime] => 0
    [statslastweekly] => 1233532800
    [statslastmonthly] => 1233446400
    [email_trackbymail] => 1
    [email_marriedfolders2courses] => 1
    [email_max_number_courses] => 0
    [statsruntimedays] => 31
    [verifychangedemail] => 0
    [recaptchapublickey] => 
    [recaptchaprivatekey] => 
    [grade_report_user_showpercentage] => 2
    [profilesforenrolledusersonly] => 0
    [emailchangeconfirmation] => 0
    [enablenotes] => 1
    [formatstringstriptags] => 1
    [getremoteaddrconf] => 0
    [deleteincompleteusers] => 0
    [email_answered_color] => #83CC83
    [email_table_field_color] => #B7B7B7
    [email_old_select_participants] => 0
    [email_add_admins] => 1
    [statslastexecution] => 1234401408
    [statsrunning] => 1234487808
    [block_library_resources_title] => Library Resources
    [block_library_resources_window] => 1
    [grade_navmethod] => 2
    [unlimitedgrades] => 0
    [grade_aggregations_visible] => 0,10,11,12,2,4,6,8,13
    [grade_report_fixedstudents] => 1
    [forum_ajaxrating] => 0
    [enablecalendarexport] => 1
    [calendar_exportsalt] => 8tDZjqe2VuBDWEsock010q2BxIS03cW2KmT6QyWKAvsclT2lRfkEwRTMKgMh
    [mycoursesperpage] => 1000
    [maxcategorydepth] => 0
    [extramemorylimit] => 512M
    [exercise_initialdisable] => 1
    [courserequestnotify] => 2
    [enrol_manual_keyholderrole] => 64
    [enablesafebrowserintegration] => 0
    [turnitin_account_id] => 2702
    [turnitin_subaccount_id] => 
    [turnitin_secretkey] => uc2703LM
    [turnitin_apiurl] => https://api.turnitinuk.com/api.asp
    [turnitin_usegrademark] => 1
    [turnitin_useanon] => 1
    [turnitin_studentemail] => 0
    [turnitin_enablediagnostic] => 0
    [turnitin_agreement] => <p><strong>DECLARATION OF OWNERSHIP:</strong></p>
<ul>
<li>I confirm that I have read and understood the guidelines on plagiarism, that I understand the meaning of plagiarism and that I may be penalised for submitting work that has been plagiarised.</li>
<li>I confirm that all work will also be submitted electronically and that this can be checked using the JISC detection service, Turnitin®.</li>
<li>If I have been asked to submit hard copy, I understand that the work cannot be assessed unless both hard copy and electronic versions of the work are handed in.</li>
<li>I declare that all material presented in the accompanying work is entirely my own work except where explicitly and individually indicated and that all sources used in its preparation and all quotations are clearly cited.</li>
</ul>
    [passwordpolicy] => 1
    [enableimsccimport] => 0
    [grade_report_overview_showtotalsifcontainhidden] => 0
    [grade_report_user_showtotalsifcontainhidden] => 0
    [turnitin_proxyurl] => 
    [turnitin_proxyport] => 
    [turnitin_proxyuser] => 
    [turnitin_proxypassword] => 
    [block_timetable_title] => Common Timetable
    [block_timetable_window] => 1
    [block_rss_client_num_entries] => 5
    [block_rss_client_timeout] => 1000
    [block_rss_client_submitters] => 1
    [turnitin_userepository] => 0
    [filter_mediaplugin_enable_ogv] => 1
    [filter_mediaplugin_enable_ogg] => 1
    [turnitin_useerater] => 0
    [turnitin_tutoremail] => 1
    [turnitin_receiptemail] => 1
    [forceloginforprofileimage] => 0
    [loginpasswordautocomplete] => 0
    [maintenance_enabled] => 0
    [jsrev] => 1487933493
    [themerev] => 1487933493
    [stringfilters] => 
    [texteditors] => atto,tinymce,textarea
    [licenses] => unknown
    [sitedefaultlicense] => unknown
    [siteadmins] => 53879,174,61251,8095,208863,252533,40237,314623,350553,280,37926,371563,441393,250699,372293,58813,340713,62631,372753,490583
    [coursecontact] => 7,3,111
    [groupenrolmentkeypolicy] => 0
    [enableavailability] => 1
    [enablecompletion] => 1
    [siteguest] => 1135
    [usecomments] => 1
    [enableportfolios] => 1
    [enablewebservices] => 1
    [messaginghidereadnotifications] => 0
    [messagingdeletereadnotificationsdelay] => 604800
    [enableplagiarism] => 0
    [restorernewroleid] => 7
    [showuseridentity] => idnumber,email,department
    [enablegravatar] => 0
    [grade_report_enableajax] => 1
    [grade_report_showanalysisicon] => 1
    [grade_report_user_showgrade] => 1
    [grade_report_user_showfeedback] => 1
    [grade_report_user_showrange] => 1
    [grade_report_user_showweight] => 1
    [grade_report_user_showaverage] => 0
    [grade_report_user_showlettergrade] => 0
    [grade_report_user_rangedecimals] => 0
    [defaultcity] => 
    [allcountrycodes] => 
    [langstringcache] => 1
    [feedback_allowfullanonymous] => 1
    [forum_maxattachments] => 9
    [hotpot_enablemymoodle] => 1
    [hotpot_enablecache] => 1
    [hotpot_enablecron] => 
    [hotpot_enableswf] => 1
    [hotpot_enableobfuscate] => 1
    [hotpot_frameheight] => 85
    [hotpot_lockframe] => 0
    [hotpot_storedetails] => 0
    [hotpot_maxeventlength] => 5
    [turnitin_default_type] => 1
    [turnitin_default_numparts] => 1
    [turnitin_default_grade] => 100
    [turnitin_default_anon] => 1
    [turnitin_default_studentreports] => 1
    [turnitin_default_allowlate] => 1
    [turnitin_default_reportgenspeed] => 1
    [turnitin_default_submitpapersto] => 1
    [turnitin_default_spapercheck] => 1
    [turnitin_default_internetcheck] => 1
    [turnitin_default_journalcheck] => 1
    [turnitin_default_excludebiblio] => 1
    [turnitin_default_excludequoted] => 1
    [trimlength] => 50
    [block_course_menu_sitetitle] => Menu
    [block_course_menu_docked_background] => #00AEEF
    [block_echo360_configuration_echosystem_url] => https://lcess1.uclw.ucl.ac.uk:8443/
    [block_echo360_configuration_trusted_system_consumer_key] => moodle2production
    [block_echo360_configuration_trusted_system_consumer_secret] => ggtKioAfEtsniAb5l84lSAW/uywjE260bxUyho8K8pXgKbeOJOa0CkRAPWJqFZ3HsgieG27bhPttno0M7+fOmg==
    [block_echo360_configuration_security_realm] => default
    [block_echo360_configuration_moodle_external_id_field] => idnumbercourse
    [block_quickmail_allowstudents] => 0
    [block_quickmail_roleselection] => 7,3,4,5,26
    [block_tags_showcoursetags] => 0
    [jabberhost] => 
    [jabberserver] => 
    [jabberusername] => 
    [jabberpassword] => 
    [jabberport] => 5222
    [authpreventaccountcreation] => 0
    [loginpageautofocus] => 0
    [portfolio_moderate_filesize_threshold] => 1048576
    [portfolio_high_filesize_threshold] => 5242880
    [portfolio_moderate_db_threshold] => 20
    [portfolio_high_db_threshold] => 50
    [repositorycacheexpire] => 120
    [repositoryallowexternallinks] => 1
    [legacyfilesinnewcourses] => 0
    [enablewsdocumentation] => 0
    [allowbeforeblock] => 0
    [allowedip] => 
    [blockedip] => 
    [profileroles] => 96,7,3,4,5,26,24
    [userquota] => 31457280
    [sitepolicyguest] => https://moodle.ucl.ac.uk/pluginfile.php/1/theme_ucl/usepolicy/1442233325/UCL_Moodle_usage_policy.html
    [maxconsecutiveidentchars] => 0
    [rememberusername] => 0
    [strictformsrequired] => 0
    [cookiesecure] => 1
    [cookiehttponly] => 0
    [allowframembedding] => 0
    [themedesignermode] => 0
    [allowthemechangeonurl] => 1
    [allowblockstodock] => 1
    [custommenuitems] => Staff Help
-Login Problems?|https://wiki.ucl.ac.uk/display/MoodleResourceCentre/Moodle+Staff+FAQs#MoodleStaffFAQs-HowdoIlogin%3F "target=\"_blank
-Moodle Resource Centre|https://wiki.ucl.ac.uk/display/MoodleResourceCentre/Guides+to+using+Moodle+for+staff" target=\"_blank "target=\"_blank
-About Moodle at UCL|http://www.ucl.ac.uk/isd/staff/e-learning/core-tools/moodle/about "target=\"_blank
-FAQs|https://wiki.ucl.ac.uk/display/MoodleResourceCentre/Moodle+Staff+FAQs "target=\"_blank
-Request a Moodle Course|http://www.ucl.ac.uk/isd-extra/staff/e-learning/tools/moodle/newcourse.php "target=\"_blank
-Moodle Exam Notification|http://www.ucl.ac.uk/isd-extra/staff/e-learning/tools/moodle/exam.php "target=\"_blank
-Moodle Training|https://www.ucl.ac.uk/isd/services/learning-teaching/elearning-staff/training "target=\"_blank
-Contact Moodle Support|http://www.ucl.ac.uk/isd/services/learning-teaching/elearning-staff/about/support "target=\"_blank
-UCL Moodle User Group|https://moodle.ucl.ac.uk/course/view.php?id=46
Student Help
-Login Problems?|https://wiki.ucl.ac.uk/display/ELearningStudentSupport/Moodle+FAQs#MoodleFAQs-Whycan%27tIlogontoUCLMoodlewithmyUCLusernameandpassword%3F "target=\"_blank
-Moodle Quick Start Guide|https://wiki.ucl.ac.uk/display/ELearningStudentSupport/Moodle+Quick+Start+Guide+for+Students "target=\"_blank
-Moodle for e-Assessment|https://wiki.ucl.ac.uk/x/igWmAQ "target=\"_blank
-Learning with Technology|https://moodle.ucl.ac.uk/course/view.php?id=34285
-Plagiarism and Academic Writing|https://moodle.ucl.ac.uk/course/view.php?id=12731
-Subject area Study Skills|https://moodle.ucl.ac.uk/course/category.php?id=70
-IT training for Students|http://www.ucl.ac.uk/isd/students/training "target=\"_blank
-FAQs|https://wiki.ucl.ac.uk/display/ELearningStudentSupport/Moodle+FAQs "target=\"_blank
-Turnitin Help|https://wiki.ucl.ac.uk/display/ELearningStudentSupport/Turnitin "target=\"_blank
-More student links|http://www.ucl.ac.uk/students "target=\"_blank
Services
-Moodle Snapshot|https://moodle-snapshot.ucl.ac.uk/ "target=\"_blank
-Lynda|http://www.ucl.ac.uk/lynda "target=\"_blank
-Box of Broadcasts|http://bobnational.net/ "target=\"_blank
-Portico|http://www.ucl.ac.uk/portico "target=\"_blank
-Common Timetable|http://www.ucl.ac.uk/timetable "target=\"_blank
-Library|http://www.ucl.ac.uk/library "target=\"_blank
-MyAccount|https://myaccount.ucl.ac.uk/ "target=\"_blank
-Live@UCL Email|http://outlook.com/live.ucl.ac.uk "target=\"_blank
-MyPortfolio|https://myportfolio.ucl.ac.uk "target=\"_blank
    [enabledevicedetection] => 0
    [devicedetectregex] => []
    [useblogassociations] => 1
    [useexternalblogs] => 1
    [externalblogcrontime] => 86400
    [maxexternalblogsperuser] => 1
    [blogusecomments] => 1
    [blogshowcommentscount] => 1
    [defaulthomepage] => 1
    [navshowcategories] => 0
    [navshowallcourses] => 0
    [navcourselimit] => 20
    [usesitenameforsitepages] => 1
    [navadduserpostslinks] => 1
    [emoticons] => [{"text":":-)","imagename":"s\/smiley","imagecomponent":"core","altidentifier":"smiley","altcomponent":"core_pix"},{"text":":)","imagename":"s\/smiley","imagecomponent":"core","altidentifier":"smiley","altcomponent":"core_pix"},{"text":":-D","imagename":"s\/biggrin","imagecomponent":"core","altidentifier":"biggrin","altcomponent":"core_pix"},{"text":";-)","imagename":"s\/wink","imagecomponent":"core","altidentifier":"wink","altcomponent":"core_pix"},{"text":":-\/","imagename":"s\/mixed","imagecomponent":"core","altidentifier":"mixed","altcomponent":"core_pix"},{"text":"V-.","imagename":"s\/thoughtful","imagecomponent":"core","altidentifier":"thoughtful","altcomponent":"core_pix"},{"text":":-P","imagename":"s\/tongueout","imagecomponent":"core","altidentifier":"tongueout","altcomponent":"core_pix"},{"text":":-p","imagename":"s\/tongueout","imagecomponent":"core","altidentifier":"tongueout","altcomponent":"core_pix"},{"text":"B-)","imagename":"s\/cool","imagecomponent":"core","altidentifier":"cool","altcomponent":"core_pix"},{"text":"^-)","imagename":"s\/approve","imagecomponent":"core","altidentifier":"approve","altcomponent":"core_pix"},{"text":"8-)","imagename":"s\/wideeyes","imagecomponent":"core","altidentifier":"wideeyes","altcomponent":"core_pix"},{"text":":o)","imagename":"s\/clown","imagecomponent":"core","altidentifier":"clown","altcomponent":"core_pix"},{"text":":-(","imagename":"s\/sad","imagecomponent":"core","altidentifier":"sad","altcomponent":"core_pix"},{"text":":(","imagename":"s\/sad","imagecomponent":"core","altidentifier":"sad","altcomponent":"core_pix"},{"text":"8-.","imagename":"s\/shy","imagecomponent":"core","altidentifier":"shy","altcomponent":"core_pix"},{"text":":-I","imagename":"s\/blush","imagecomponent":"core","altidentifier":"blush","altcomponent":"core_pix"},{"text":":-X","imagename":"s\/kiss","imagecomponent":"core","altidentifier":"kiss","altcomponent":"core_pix"},{"text":"8-o","imagename":"s\/surprise","imagecomponent":"core","altidentifier":"surprise","altcomponent":"core_pix"},{"text":"P-|","imagename":"s\/blackeye","imagecomponent":"core","altidentifier":"blackeye","altcomponent":"core_pix"},{"text":"8-[","imagename":"s\/angry","imagecomponent":"core","altidentifier":"angry","altcomponent":"core_pix"},{"text":"(grr)","imagename":"s\/angry","imagecomponent":"core","altidentifier":"angry","altcomponent":"core_pix"},{"text":"xx-P","imagename":"s\/dead","imagecomponent":"core","altidentifier":"dead","altcomponent":"core_pix"},{"text":"|-.","imagename":"s\/sleepy","imagecomponent":"core","altidentifier":"sleepy","altcomponent":"core_pix"},{"text":"}-]","imagename":"s\/evil","imagecomponent":"core","altidentifier":"evil","altcomponent":"core_pix"},{"text":"(h)","imagename":"s\/heart","imagecomponent":"core","altidentifier":"heart","altcomponent":"core_pix"},{"text":"(heart)","imagename":"s\/heart","imagecomponent":"core","altidentifier":"heart","altcomponent":"core_pix"},{"text":"(y)","imagename":"s\/yes","imagecomponent":"core","altidentifier":"yes","altcomponent":"core"},{"text":"(n)","imagename":"s\/no","imagecomponent":"core","altidentifier":"no","altcomponent":"core"},{"text":"(martin)","imagename":"s\/martin","imagecomponent":"core","altidentifier":"martin","altcomponent":"core_pix"},{"text":"( )","imagename":"s\/egg","imagecomponent":"core","altidentifier":"egg","altcomponent":"core_pix"}]
    [courselistshortnames] => 0
    [useexternalyui] => 1
    [yuicomboloading] => 1
    [cachejs] => 1
    [additionalhtmlhead] => 
    [additionalhtmltopofbody] => 
    [additionalhtmlfooter] => 
    [commentsperpage] => 0
    [pathtodot] => 
    [sessioncookiedomain] => 
    [proxybypass] => localhost, 127.0.0.1
    [maintenance_message] => <p><strong><span style="font-size: medium;">29th July</span><span style="font-size: medium;"><br></span></strong></p>
<p>UCL Moodle is currently undergoing <b>scheduled maintenance</b>, and will be available again at 9:00 <br></p><p>We appreciate your patience.</p>
<p><span style="line-height: 1.5;">&nbsp;</span></p>
<p><span style="line-height: 1.5;">Learning and Teaching Applications Team,</span></p>
<p>Information Services Division</p>
    [logguests] => 1
    [curlcache] => 120
    [curltimeoutkbitrate] => 56
    [mnetprofileexportfields] => city,country,lang,timezone,picture,description,mailformat,maildigest,maildisplay
    [mnetprofileimportfields] => city,country,lang,timezone,picture,description,mailformat,maildigest,maildisplay
    [debugstringids] => 0
    [debugvalidators] => 0
    [debugpageinfo] => 0
    [fileslastcleanup] => 1479996416
    [webserviceprotocols] => rest,xmlrpc
    [enablemobilewebservice] => 1
    [turnitin_enablepseudo] => 0
    [siteidentifier] => eLowuTlQw4dfa3rUKHpmBCiYi982hvjPmoodle.ucl.ac.uk
    [block_course_menu_global_config] => O:8:"stdClass":5:{s:14:"expandableTree";i:0;s:11:"linksEnable";i:0;s:10:"trimlength";i:20;s:8:"elements";a:10:{i:0;a:7:{s:2:"id";s:4:"tree";s:4:"name";s:14:"Topics / Weeks";s:3:"url";s:0:"";s:4:"icon";s:0:"";s:7:"canHide";i:0;s:7:"visible";i:1;s:10:"expandable";i:0;}i:1;a:7:{s:2:"id";s:15:"showallsections";s:4:"name";s:17:"Show All Sections";s:3:"url";s:0:"";s:4:"icon";s:61:"https://moodle.ucl.ac.uk/blocks/course_menu/icons/viewall.gif";s:7:"canHide";i:1;s:7:"visible";i:0;s:10:"expandable";i:0;}i:2;a:7:{s:2:"id";s:8:"calendar";s:4:"name";s:8:"Calendar";s:3:"url";s:0:"";s:4:"icon";s:57:"https://moodle.ucl.ac.uk/blocks/course_menu/icons/cal.gif";s:7:"canHide";i:1;s:7:"visible";i:0;s:10:"expandable";i:0;}i:3;a:7:{s:2:"id";s:9:"sitepages";s:4:"name";s:10:"Site pages";s:3:"url";s:0:"";s:4:"icon";s:0:"";s:7:"canHide";i:1;s:7:"visible";i:0;s:10:"expandable";i:0;}i:4;a:7:{s:2:"id";s:9:"myprofile";s:4:"name";s:10:"My profile";s:3:"url";s:0:"";s:4:"icon";s:0:"";s:7:"canHide";i:1;s:7:"visible";i:0;s:10:"expandable";i:0;}i:5;a:7:{s:2:"id";s:9:"mycourses";s:4:"name";s:10:"My courses";s:3:"url";s:0:"";s:4:"icon";s:0:"";s:7:"canHide";i:1;s:7:"visible";i:0;s:10:"expandable";i:0;}i:6;a:7:{s:2:"id";s:17:"myprofilesettings";s:4:"name";s:19:"My profile settings";s:3:"url";s:0:"";s:4:"icon";s:0:"";s:7:"canHide";i:1;s:7:"visible";i:0;s:10:"expandable";i:0;}i:7;a:7:{s:2:"id";s:20:"courseadministration";s:4:"name";s:21:"Course administration";s:3:"url";s:0:"";s:4:"icon";s:0:"";s:7:"canHide";i:1;s:7:"visible";i:0;s:10:"expandable";i:0;}i:8;a:7:{s:2:"id";s:12:"participants";s:4:"name";s:12:"Participants";s:3:"url";s:0:"";s:4:"icon";s:0:"";s:7:"canHide";i:1;s:7:"visible";i:1;s:10:"expandable";i:0;}i:9;a:7:{s:2:"id";s:7:"reports";s:4:"name";s:7:"Reports";s:3:"url";s:0:"";s:4:"icon";s:0:"";s:7:"canHide";i:1;s:7:"visible";i:1;s:10:"expandable";i:0;}}s:5:"links";a:0:{}}
    [turnitin_transmatch] => 0
    [gravatardefaulturl] => mm
    [block_quickmail_receipt] => 0
    [block_quickmail_prepend_class] => shortname
    [block_quickmail_ferpa] => strictferpa
    [langrev] => 1487933493
    [messagingallowemailoverride] => 1
    [enableblogs] => 1
    [branch] => 31
    [core_media_enable_html5video] => 1
    [core_media_enable_html5audio] => 1
    [core_media_enable_mp3] => 1
    [core_media_enable_flv] => 1
    [core_media_enable_wmp] => 1
    [core_media_enable_qt] => 1
    [core_media_enable_rm] => 1
    [core_media_enable_youtube] => 1
    [core_media_enable_vimeo] => 0
    [core_media_enable_swf] => 1
    [requestcategoryselection] => 0
    [grade_export_userprofilefields] => idnumber,firstname,lastname,username,department,email
    [grade_export_customprofilefields] => 
    [recovergradesdefault] => 0
    [googlemapkey3] => 
    [hotpot_bodystyles] => 
    [scheduler_maxstudentsperslot] => 25
    [block_course_menu_trimlength] => 20
    [block_html_allowcssclasses] => 0
    [smtpsecure] => 
    [mobilecssurl] => 
    [qtype_algebra_method] => eval
    [qtype_algebra_host] => localhost
    [qtype_algebra_port] => 7777
    [qtype_algebra_uri] => 
    [allowguestmymoodle] => 1
    [navshowmycoursecategories] => 0
    [navsortmycoursessort] => fullname
    [linkadmincategories] => 0
    [navshowfrontpagemods] => 1
    [courseswithsummarieslimit] => 10
    [modchooserdefault] => 1
    [updateautocheck] => 1
    [updateminmaturity] => 200
    [updatenotifybuilds] => 0
    [dndallowtextandlinks] => 0
    [enablecssoptimiser] => 0
    [updatecronoffset] => 12012
    [portfolio_moderate_dbsize_threshold] => 10
    [portfolio_high_dbsize_threshold] => 50
    [filesrootrecordsfixed] => 1
    [localcachedirpurged] => 1487933493
    [movingmoduleupgradescriptwasrun] => 1
    [allversionshash] => 8f273f2c358d13a4e620874af4c6a537010a7d3a
    [completiondefault] => 1
    [enablebadges] => 1
    [maxusersperpage] => 100
    [grade_report_showonlyactiveenrol] => 1
    [badges_defaultissuername] => UCL Moodle
    [badges_defaultissuercontact] => ccaalts@ucl.ac.uk
    [badges_badgesalt] => badges0
    [badges_allowexternalbackpack] => 1
    [badges_allowcoursebadges] => 1
    [forum_trackingtype] => 1
    [forum_allowforcedreadtracking] => 0
    [allowattachments] => 1
    [legacyfilesaddallowed] => 0
    [lockoutthreshold] => 0
    [lockoutwindow] => 1800
    [lockoutduration] => 1800
    [pwresettime] => 1800
    [calendartype] => gregorian
    [calendar_customexport] => 1
    [calendar_exportlookahead] => 365
    [calendar_exportlookback] => 5
    [calendar_showicalsource] => 1
    [navshowfullcoursenames] => 0
    [courseoverviewfileslimit] => 1
    [courseoverviewfilesext] => .jpg,.gif,.png
    [modeditingmenu] => 1
    [blockeditingmenu] => 1
    [frontpagecourselimit] => 200
    [emailonlyfromnoreplyaddress] => 1
    [qtype_algebra_texdelimiters] => old
    [profilingenabled] => 0
    [profilingincluded] => 
    [profilingexcluded] => 
    [profilingautofrec] => 0
    [profilingallowme] => 0
    [profilingallowall] => 0
    [profilinglifetime] => 1440
    [profilingimportprefix] => (I)
    [undeletableblocktypes] => navigation,settings,course_visibility,portico_enrolments,mentees
    [campuspack_user_agent] => Campus Pack Fusion Moodle Integration/4.12.1.d52e26480dd8bc558e308504a30cd28d8751f963-HEAD-3.1
    [campuspack_moodle_two] => 1
    [elluminate_server] => 
    [elluminate_auth_username] => UCLEUMOODLEPROD
    [elluminate_auth_password] => h5en4i1
    [elluminate_boundary_default] => 15
    [elluminate_pre_populate_moderators] => 1
    [elluminate_permissions_on] => 1
    [elluminate_raise_hand] => 0
    [elluminate_all_moderators] => 0
    [elluminate_must_be_supervised] => 0
    [elluminate_max_talkers] => 6
    [elluminate_ws_debug] => 0
    [elluminate_log_level] => 4
    [campuspack_server_id] => ucl-moodle
    [campuspack_hmac_key] => f33e199d67c0f026da72970e0f2baa51bc2886f0
    [campuspack_oauth_id] => 
    [campuspack_oauth_key] => 
    [campuspack_server_url] => https://ucl-ac-uk.campuspack.eu/
    [campuspack_server_communication_url] => 
    [campuspack_auto_roster_sync] => 1
    [campuspack_auto_sync_users] => 
    [campuspack_content_types] => 
    [qtype_jme_options] => 
    [scheduledtaskreset] => 1487933493
    [pathtogs] => /usr/bin/gs
    [show_sumofgrades_upgrade_132] => 1
    [show_sumofgrades_upgrade_200] => 1
    [show_sumofgrades_upgrade_1942] => 1
    [show_sumofgrades_upgrade_2485] => 1
    [show_sumofgrades_upgrade_2495] => 1
    [show_sumofgrades_upgrade_2499] => 1
    [show_sumofgrades_upgrade_2987] => 1
    [show_sumofgrades_upgrade_4523] => 1
    [show_sumofgrades_upgrade_5395] => 1
    [show_sumofgrades_upgrade_5397] => 1
    [show_sumofgrades_upgrade_5647] => 1
    [show_sumofgrades_upgrade_6916] => 1
    [show_sumofgrades_upgrade_7207] => 1
    [show_sumofgrades_upgrade_7640] => 1
    [show_sumofgrades_upgrade_10585] => 1
    [show_sumofgrades_upgrade_11101] => 1
    [show_sumofgrades_upgrade_11113] => 1
    [show_sumofgrades_upgrade_16449] => 1
    [show_sumofgrades_upgrade_17331] => 1
    [show_sumofgrades_upgrade_17337] => 1
    [show_sumofgrades_upgrade_18390] => 1
    [show_sumofgrades_upgrade_19068] => 1
    [show_sumofgrades_upgrade_21921] => 1
    [show_sumofgrades_upgrade_29975] => 1
    [show_sumofgrades_upgrade_30099] => 1
    [grades_sumofgrades_upgrade_flagged] => 1
    [show_aggregatesubcats_upgrade_8540] => 1
    [show_aggregatesubcats_upgrade_9713] => 1
    [show_aggregatesubcats_upgrade_18195] => 1
    [show_aggregatesubcats_upgrade_23163] => 1
    [show_aggregatesubcats_upgrade_26811] => 1
    [show_aggregatesubcats_upgrade_27819] => 1
    [defaultpreference_maildisplay] => 2
    [defaultpreference_mailformat] => 1
    [defaultpreference_maildigest] => 0
    [defaultpreference_autosubscribe] => 1
    [defaultpreference_trackforums] => 0
    [alternativefullnameformat] => language
    [grade_report_showmin] => 1
    [gradepointmax] => 100
    [gradepointdefault] => 100
    [grade_overridecat] => 1
    [grade_report_historyperpage] => 50
    [grade_report_user_showcontributiontocoursetotal] => 1
    [authloginviaemail] => 0
    [airnotifierurl] => https://messages.moodle.net
    [airnotifierport] => 443
    [airnotifiermobileappname] => com.moodle.moodlemobile
    [airnotifierappname] => commoodlemoodlemobile
    [airnotifieraccesskey] => 
    [repositorygetfiletimeout] => 30
    [repositorysyncfiletimeout] => 1
    [repositorysyncimagetimeout] => 3
    [customusermenuitems] => grades,grades|/grade/report/mygrades.php|grades
messages,message|/message/index.php|message
preferences,moodle|/user/preferences.php|preferences
    [navexpandmycourses] => 1
    [doclang] => 
    [maxtimelimit] => 0
    [messageinbound_enabled] => 0
    [messageinbound_mailbox] => 
    [messageinbound_domain] => 
    [messageinbound_host] => 
    [messageinbound_hostssl] => ssl
    [messageinbound_hostuser] => 
    [messageinbound_hostpass] => 
    [elluminate_scheduler] => SAS
    [elluminate_last_license_check] => 1479996644
    [elluminate_last_cron_run] => 1479996619
    [elluminate_telephony] => -1
    [show_min_max_grades_changed_3807] => 1
    [show_min_max_grades_changed_3139] => 1
    [show_min_max_grades_changed_8668] => 1
    [show_min_max_grades_changed_2819] => 1
    [show_min_max_grades_changed_5407] => 1
    [show_min_max_grades_changed_8152] => 1
    [show_min_max_grades_changed_4215] => 1
    [show_min_max_grades_changed_7704] => 1
    [show_min_max_grades_changed_10931] => 1
    [show_min_max_grades_changed_10933] => 1
    [show_min_max_grades_changed_945] => 1
    [show_min_max_grades_changed_11275] => 1
    [show_min_max_grades_changed_11793] => 1
    [show_min_max_grades_changed_5647] => 1
    [show_min_max_grades_changed_2350] => 1
    [show_min_max_grades_changed_12619] => 1
    [show_min_max_grades_changed_5173] => 1
    [show_min_max_grades_changed_10211] => 1
    [show_min_max_grades_changed_4523] => 1
    [show_min_max_grades_changed_16209] => 1
    [show_min_max_grades_changed_18186] => 1
    [show_min_max_grades_changed_19488] => 1
    [show_min_max_grades_changed_20760] => 1
    [show_min_max_grades_changed_6977] => 1
    [show_min_max_grades_changed_21741] => 1
    [show_min_max_grades_changed_21241] => 1
    [show_min_max_grades_changed_21915] => 1
    [show_min_max_grades_changed_13091] => 1
    [show_min_max_grades_changed_23502] => 1
    [show_min_max_grades_changed_23484] => 1
    [show_min_max_grades_changed_23487] => 1
    [show_min_max_grades_changed_24474] => 1
    [show_min_max_grades_changed_23505] => 1
    [show_min_max_grades_changed_24960] => 1
    [show_min_max_grades_changed_7460] => 1
    [show_min_max_grades_changed_190] => 1
    [show_min_max_grades_changed_8416] => 1
    [show_min_max_grades_changed_24804] => 1
    [show_min_max_grades_changed_23712] => 1
    [show_min_max_grades_changed_2021] => 1
    [show_min_max_grades_changed_921] => 1
    [show_min_max_grades_changed_12140] => 1
    [show_min_max_grades_changed_23070] => 1
    [show_min_max_grades_changed_972] => 1
    [show_min_max_grades_changed_26353] => 1
    [show_min_max_grades_changed_27201] => 1
    [show_min_max_grades_changed_27229] => 1
    [show_min_max_grades_changed_4561] => 1
    [show_min_max_grades_changed_23493] => 1
    [show_min_max_grades_changed_23388] => 1
    [show_min_max_grades_changed_23391] => 1
    [show_min_max_grades_changed_23490] => 1
    [show_min_max_grades_changed_22401] => 1
    [show_min_max_grades_changed_24147] => 1
    [show_min_max_grades_changed_26759] => 1
    [show_min_max_grades_changed_27277] => 1
    [show_min_max_grades_changed_26757] => 1
    [show_min_max_grades_changed_9050] => 1
    [show_min_max_grades_changed_18198] => 1
    [show_min_max_grades_changed_26129] => 1
    [show_min_max_grades_changed_13991] => 1
    [show_min_max_grades_changed_6679] => 1
    [show_min_max_grades_changed_26763] => 1
    [show_min_max_grades_changed_26761] => 1
    [show_min_max_grades_changed_3863] => 1
    [show_min_max_grades_changed_29381] => 1
    [show_min_max_grades_changed_18324] => 1
    [upgrade_minmaxgradestepignored] => 1
    [upgrade_extracreditweightsstepignored] => 1
    [gradebook_calculations_freeze_27095] => 20150627
    [gradebook_calculations_freeze_17337] => 20150627
    [gradebook_calculations_freeze_29431] => 20150627
    [upgrade_calculatedgradeitemsignored] => 1
    [grade_minmaxtouse] => 1
    [campuspack_init] => 1
    [campuspack_role_admin] => administrator
    [campuspack_role_coursecreator] => instructor
    [campuspack_role_editingteacher] => instructor
    [campuspack_role_teacher] => instructor
    [campuspack_role_student] => student
    [campuspack_role_guest] => student
    [campuspack_role_user] => user
    [campuspack_archetype_admin] => administrator
    [campuspack_archetype_coursecreator] => staff
    [campuspack_archetype_editingteacher] => faculty
    [campuspack_archetype_teacher] => faculty
    [campuspack_archetype_student] => student
    [campuspack_archetype_guest] => user
    [campuspack_archetype_user] => user
    [campuspack_error_ReplayDetected] => A token replay was detected.  Please contact the Campus Pack administrator.
    [campuspack_error_Unauthenticated] => You are unauthenticated to Campus Pack.  Please contact a system administrator.
    [campuspack_error_SSOFailed] => Single sign on failure.  Please contact the Campus Pack administrator.
    [campuspack_content_to_course_11] => UCL Arena Digital
    [campuspack_content_to_course_25] => Janina's
    [campuspack_content_to_course_13] => Domi's test course 25th August 
    [campuspack_content_to_course_15] => 28 upgrade test course 
    [campuspack_content_to_course_31] => LCLLG162A
    [campuspack_content_to_course_17] => CPASG552A
    [campuspack_content_to_course_5] => UCL Arena Digital
    [campuspack_content_to_course_3] => UCL Arena Digital
    [campuspack_content_to_course_33] => Janina's
    [campuspack_content_to_course_23] => COMP101P
    [campuspack_content_to_course_1] => Tim Neumann test course
    [campuspack_content_to_course_7] => UCL Arena Digital
    [campuspack_content_to_course_9] => UCL Arena Digital
    [campuspack_content_to_course_27] => Janina's
    [campuspack_content_to_course_29] => LCLLG162A
    [campuspack_content_to_course_35] => Janina's
    [campuspack_content_to_course_39] => Janina's
    [campuspack_content_to_course_41] => Anthony Grout Test Course
    [campuspack_content_to_course_43] => UCL Arena Digital
    [campuspack_content_to_course_45] => Domi's test course 25th August 
    [campuspack_link_content_2059713] => Primary_Submission/2059713
    [campuspack_content_to_course_47] => Primary_SP
    [campuspack_link_content_2059725] => Primary_Submission/2059725
    [campuspack_content_to_course_49] => MedicalPhysicsNoticeboard
    [campuspack_link_content_2059729] => Primary_Submission/2059729
    [campuspack_content_to_course_51] => CCMEG272A
    [campuspack_link_content_2059733] => Primary_Submission/2059733
    [campuspack_content_to_course_53] => TMALEASTFI01
    [campuspack_link_content_2059737] => Primary_Submission/2059737
    [campuspack_content_to_course_55] => UCL Arena Digital
    [campuspack_link_content_2059743] => Primary_Submission/2059743
    [campuspack_content_to_course_57] => HCSCGS03
    [campuspack_link_content_2059747] => Primary_Submission/2059747
    [campuspack_content_to_course_59] => ESPS Administration
    [campuspack_link_content_2059753] => Primary_Submission/2059753
    [campuspack_content_to_course_61] => ECON3012
    [campuspack_content_to_course_21] => COMP101P
    [campuspack_content_to_course_69] => UCL Laws Careers
    [campuspack_content_to_course_71] => Academic Writing Centre: Referencing and Citation (Online)
    [campuspack_content_to_course_73] => 28 upgrade test course 
    [campuspack_content_to_course_77] => HSSCG132B
    [campuspack_content_to_course_79] => ITAL1116
    [campuspack_content_to_course_37] => Janina's
    [campuspack_link_content_2070225] => Primary_Submission/2070225
    [campuspack_content_to_course_81] => TEPPCOSMNF01
    [campuspack_content_to_course_85] => CPASG671B
    [campuspack_content_to_course_87] => HSSCG241A
    [campuspack_content_to_course_93] => SoP-ELDG
    [campuspack_content_to_course_95] => Domi Sinclair (GSWM 7TH November)
    [campuspack_content_to_course_19] => COMP101P
    [campuspack_content_to_course_109] => 28 upgrade test course 
    [campuspack_content_to_course_63] => MB
    [campuspack_content_to_course_65] => CPASG671B
    [campuspack_content_to_course_67] => CPASG671B
    [campuspack_content_to_course_111] => RDTCZ
    [campuspack_content_to_course_75] => UCL Arena digital practice space 1
    [campuspack_link_content_2090511] => Janina's/2090511
    [campuspack_link_content_2090527] => Janina's/2090527
    [campuspack_link_content_2090545] => Janina's/2090545
    [campuspack_content_to_course_119] => SoP-ELDG-Test-A
    [campuspack_content_to_course_121] => SoP-ELDG-Test-A
    [campuspack_content_to_course_123] => SoP-ELDG-Test-A
    [campuspack_content_to_course_129] => MPHY3013/MPHYM013
    [campuspack_content_to_course_133] => INSTG044
    [campuspack_content_to_course_135] => Academic Writing Centre: Referencing and Citation (Online)
    [campuspack_content_to_course_139] => BASC2001
    [campuspack_content_to_course_83] => Academic Writing Centre: Referencing and Citation (Online)
    [campuspack_content_to_course_141] => BASC2001
    [campuspack_content_to_course_89] => Alan Seatwo Test Course
    [campuspack_content_to_course_143] => BASC2001
    [campuspack_content_to_course_145] => BASC2001
    [campuspack_content_to_course_147] => LAWSG168
    [campuspack_content_to_course_151] => ECON1001_2015/16
    [campuspack_content_to_course_97] => UCL Arena Digital
    [campuspack_content_to_course_153] => STAT2003/STAT3102
    [campuspack_content_to_course_155] => Elinor Jones test course
    [campuspack_content_to_course_157] => BENVGPD5
    [campuspack_content_to_course_99] => SoP-ELDG-Test-A
    [campuspack_content_to_course_159] => MatthewSmithPoC
    [campuspack_content_to_course_101] => RDTCZ
    [campuspack_content_to_course_161] => HSSCG241A
    [campuspack_content_to_course_165] => LCLLG181C
    [campuspack_content_to_course_103] => Elf's
    [campuspack_content_to_course_167] => SoP-ELE
    [campuspack_content_to_course_169] => Elf's
    [campuspack_content_to_course_113] => SoP-ELDG-Test-A
    [campuspack_content_to_course_115] => SoP-ELDG-Test-A
    [campuspack_content_to_course_171] => TMAEDUSEID01
    [campuspack_content_to_course_173] => Domi Sinclair (GSWM 7TH November)
    [campuspack_content_to_course_117] => SoP-ELDG-Test-A
    [campuspack_content_to_course_175] => Andrew King
    [campuspack_content_to_course_179] => LAWSG168
    [campuspack_content_to_course_183] => LAWSG168
    [campuspack_content_to_course_185] => HIST6410
    [campuspack_content_to_course_125] => MPHY202P
    [campuspack_content_to_course_127] => FIOER205B
    [campuspack_content_to_course_137] => ITAL1116
    [campuspack_content_to_course_187] => RDTCZ
    [campuspack_content_to_course_189] => Domi Sinclair (GSWM 7TH November)
    [campuspack_content_to_course_191] => Tim Neumann test course
    [campuspack_content_to_course_193] => LCLLG181CG
    [campuspack_content_to_course_177] => Clive Young GSWM
    [campuspack_content_to_course_197] => LCLLG181CG
    [campuspack_content_to_course_199] => LCLLG181CG
    [campuspack_content_to_course_205] => LCLLG181CG
    [campuspack_content_to_course_207] => STEPGP05
    [campuspack_content_to_course_209] => BENVGSC3 - Smart Cities: Context, Policy & Government
    [campuspack_content_to_course_215] => STEPGP99
    [campuspack_content_to_course_213] => STEPGP99
    [campuspack_content_to_course_217] => Elf's
    [campuspack_content_to_course_91] => SoP-ELDG
    [campuspack_content_to_course_181] => HSSCG131A
    [campuspack_content_to_course_219] => 2016HTCTW
    [campuspack_content_to_course_223] => CCMEG252C
    [campuspack_content_to_course_225] => Elf's
    [campuspack_content_to_course_237] => Mira Playpen
    [campuspack_content_to_course_239] => Mira Playpen
    [campuspack_content_to_course_241] => ARCL3097
    [campuspack_content_to_course_243] => DrugDesign
    [campuspack_content_to_course_245] => Elf's
    [campuspack_content_to_course_247] => HSSCG132B
    [campuspack_content_to_course_249] => George's PlayGround
    [campuspack_content_to_course_195] => LCLLG181CG
    [campuspack_content_to_course_259] => CPASG382B
    [campuspack_content_to_course_261] => ABConline
    [campuspack_content_to_course_263] => ECON7004
    [campuspack_content_to_course_267] => SoP-ELDG
    [campuspack_content_to_course_131] => SoP-ELDG
    [campuspack_content_to_course_273] => HSSCG203C
    [campuspack_content_to_course_277] => HSSCG132B
    [campuspack_content_to_course_201] => LCLLG181CG
    [campuspack_content_to_course_203] => LCLLG181CG
    [campuspack_content_to_course_287] => DECCPF
    [campuspack_content_to_course_289] => DECCPF
    [campuspack_content_to_course_255] => DECCPF
    [campuspack_content_to_course_295] => HSSCG132B
    [campuspack_content_to_course_297] => GERM1001
    [campuspack_content_to_course_299] => ITAL1116
    [campuspack_content_to_course_301] => ITAL1116
    [campuspack_content_to_course_303] => HSSCG212B
    [campuspack_content_to_course_305] => HSSCG212B
    [campuspack_content_to_course_307] => ECON7008
    [campuspack_content_to_course_107] => SoP-ELDG-Test-A
    [campuspack_content_to_course_265] => RDTCZ
    [campuspack_content_to_course_309] => ECON7008
    [campuspack_content_to_course_271] => BENVGSC3 - Smart Cities: Context, Policy & Government
    [campuspack_link_content_2256651] => SoP-ELDG-Test-A/2256651
    [campuspack_link_content_2256659] => SoP-ELDG-Test-A/2256659
    [campuspack_link_content_2256663] => SoP-ELDG-Test-A/2256663
    [campuspack_link_content_2256667] => SoP-ELDG-Test-A/2256667
    [campuspack_content_to_course_311] => ECON7008
    [campuspack_content_to_course_313] => ECON7008
    [campuspack_content_to_course_315] => ECON7008
    [campuspack_content_to_course_317] => ECON7008
    [campuspack_content_to_course_319] => ECON7008
    [campuspack_content_to_course_321] => HIST6410
    [campuspack_content_to_course_323] => Mira Playpen
    [campuspack_content_to_course_325] => Mira Playpen
    [campuspack_link_content_2266251] => BASC2001/2266231
    [campuspack_link_content_2266383] => BASC2001/2266231
    [campuspack_link_content_2266391] => BASC2001/2266231
    [campuspack_content_to_course_327] => TMAEDUSEID01
    [campuspack_content_to_course_329] => HSSCG132B
    [campuspack_content_to_course_275] => IPGS_MAT_2015
    [campuspack_content_to_course_333] => HSSCG132B
    [campuspack_content_to_course_279] => HSSCG132B
    [campuspack_content_to_course_281] => HSSCG132B
    [campuspack_content_to_course_283] => HSSCG132B
    [campuspack_content_to_course_337] => HSSCG212B
    [campuspack_content_to_course_163] => LCLLG181C
    [campuspack_content_to_course_341] => HSSCG211B
    [campuspack_content_to_course_345] => Jo Matthews
    [campuspack_content_to_course_351] => Pauls Test Sandpit
    [campuspack_content_to_course_355] => ARCLG104
    [campuspack_content_to_course_357] => ARCLG104
    [campuspack_content_to_course_359] => ARCLG104
    [campuspack_content_to_course_383] => HSSCG233B
    [campuspack_content_to_course_331] => HSSCG132B
    [campuspack_content_to_course_385] => CCMEG252C
    [campuspack_content_to_course_387] => Alan Seatwo Test Course
    [campuspack_content_to_course_389] => HSSCG212B
    [campuspack_content_to_course_391] => Alan Seatwo Test Course
    [campuspack_content_to_course_393] => FIOER411Y
    [campuspack_content_to_course_395] => HSSCG132B
    [campuspack_content_to_course_397] => HSSCG132B
    [campuspack_content_to_course_339] => STEPGP05
    [campuspack_content_to_course_399] => STEPGP05
    [campuspack_content_to_course_343] => Primary_PP_CICT
    [campuspack_content_to_course_405] => BENVGSC3 - Smart Cities: Context, Policy & Government
    [campuspack_content_to_course_347] => Jo Matthews
    [campuspack_content_to_course_349] => Jo Matthews
    [campuspack_content_to_course_407] => SoP-ELE
    [campuspack_content_to_course_409] => SoP-ELE
    [campuspack_content_to_course_365] => HSSCG241B
    [campuspack_content_to_course_411] => HSSCG132B
    [campuspack_content_to_course_371] => HSSCG233B
    [campuspack_content_to_course_413] => CPASGE42A: Dubai PBE
    [campuspack_content_to_course_373] => HSSCG225B
    [campuspack_content_to_course_375] => HSSCG241B
    [campuspack_content_to_course_377] => TEPSECSLAN01
    [campuspack_content_to_course_379] => HSSCG132B
    [campuspack_content_to_course_415] => HSSCG132B
    [campuspack_content_to_course_423] => HSSCG132B
    [campuspack_content_to_course_425] => George's PlayGround
    [campuspack_content_to_course_427] => HSSCG132B
    [campuspack_content_to_course_429] => HSSCG132B
    [block_quickmail_downloads] => 1
    [block_quickmail_addionalemail] => 1
    [campuspack_content_to_course_221] => 2016HTCTW
    [campuspack_content_to_course_433] => 2016HTCTW
    [campuspack_content_to_course_435] => CCMEG252C
    [campuspack_content_to_course_437] => NSEP - Summer 2016
    [campuspack_content_to_course_403] => LCEDR021X 16/17
    [campuspack_content_to_course_229] => SoP-ELE
    [antiviruses] => clamav
    [gradebook_calculations_freeze_83] => 20160518
    [gradebook_calculations_freeze_729] => 20160518
    [gradebook_calculations_freeze_752] => 20160518
    [gradebook_calculations_freeze_889] => 20160518
    [gradebook_calculations_freeze_890] => 20160518
    [gradebook_calculations_freeze_894] => 20160518
    [gradebook_calculations_freeze_895] => 20160518
    [gradebook_calculations_freeze_1144] => 20160518
    [gradebook_calculations_freeze_1201] => 20160518
    [gradebook_calculations_freeze_1202] => 20160518
    [gradebook_calculations_freeze_1943] => 20160518
    [gradebook_calculations_freeze_3097] => 20160518
    [gradebook_calculations_freeze_3417] => 20160518
    [gradebook_calculations_freeze_3523] => 20160518
    [gradebook_calculations_freeze_3737] => 20160518
    [gradebook_calculations_freeze_3739] => 20160518
    [gradebook_calculations_freeze_3763] => 20160518
    [gradebook_calculations_freeze_4493] => 20160518
    [gradebook_calculations_freeze_4535] => 20160518
    [gradebook_calculations_freeze_5561] => 20160518
    [gradebook_calculations_freeze_6141] => 20160518
    [gradebook_calculations_freeze_6916] => 20160518
    [gradebook_calculations_freeze_7255] => 20160518
    [gradebook_calculations_freeze_7448] => 20160518
    [gradebook_calculations_freeze_8058] => 20160518
    [gradebook_calculations_freeze_8066] => 20160518
    [gradebook_calculations_freeze_8444] => 20160518
    [gradebook_calculations_freeze_11099] => 20160518
    [gradebook_calculations_freeze_11101] => 20160518
    [gradebook_calculations_freeze_11103] => 20160518
    [gradebook_calculations_freeze_11105] => 20160518
    [gradebook_calculations_freeze_11107] => 20160518
    [gradebook_calculations_freeze_11109] => 20160518
    [gradebook_calculations_freeze_11111] => 20160518
    [gradebook_calculations_freeze_11113] => 20160518
    [gradebook_calculations_freeze_11119] => 20160518
    [gradebook_calculations_freeze_11397] => 20160518
    [gradebook_calculations_freeze_11569] => 20160518
    [gradebook_calculations_freeze_11955] => 20160518
    [gradebook_calculations_freeze_12009] => 20160518
    [gradebook_calculations_freeze_12017] => 20160518
    [gradebook_calculations_freeze_14805] => 20160518
    [gradebook_calculations_freeze_16341] => 20160518
    [gradebook_calculations_freeze_17568] => 20160518
    [gradebook_calculations_freeze_18741] => 20160518
    [gradebook_calculations_freeze_19269] => 20160518
    [gradebook_calculations_freeze_22061] => 20160518
    [gradebook_calculations_freeze_22133] => 20160518
    [gradebook_calculations_freeze_25949] => 20160518
    [gradebook_calculations_freeze_25957] => 20160518
    [gradebook_calculations_freeze_28279] => 20160518
    [gradebook_calculations_freeze_28281] => 20160518
    [gradebook_calculations_freeze_34275] => 20160518
    [gradebook_calculations_freeze_34305] => 20160518
    [gradebook_calculations_freeze_34827] => 20160518
    [gradebook_calculations_freeze_35313] => 20160518
    [upgrade_letterboundarycourses] => 1
    [enableglobalsearch] => 0
    [grade_mygrades_report] => overview
    [gradereport_mygradeurl] => 
    [timezone] => Europe/London
    [requiremodintro] => 0
    [forum_rsstype] => 0
    [forum_rssarticles] => 0
    [hsuforum_rsstype] => 0
    [hsuforum_rssarticles] => 0
    [allowaccountssameemail] => 0
    [limitconcurrentlogins] => 0
    [block_course_overview_hideallcourseslink] => 0
    [smtpauthtype] => LOGIN
    [searchengine] => solr
    [passwordreuselimit] => 0
    [passwordchangelogout] => 0
    [linkcoursesections] => 0
    [pathtounoconv] => /usr/bin/unoconv
    [tempdatafoldercleanup] => 168
    [dbtype] => mysqli
    [dblibrary] => native
    [dbhost] => localhost
    [dbname] => moodle_uat_20161114
    [dbuser] => mdluser_uat
    [dbpass] => Mdl@uat1
    [prefix] => mdl_
    [ucl_sf2_dbname] => moodle_sits_management_uat2
    [passwordsaltmain] => _RA0gf[t,!?uj(rD4I#8*`e:^`LMe#
    [wwwroot] => https://v31.moodle-uat.ucl.ac.uk
    [dataroot] => /data/moodledata
    [admin] => admin
    [directorypermissions] => 1535
    [sslproxy] => 1
    [noemailever] => 1
    [disableonclickaddoninstall] => 1
    [allow_mass_enroll_feature] => 1
    [behat_prefix] => behat_31_
    [behat_dataroot] => /data/moodle/behatdataroot_v31
    [behat_wwwroot] => http://moodle-uat.ucl.ac.uk/behat_v31
    [behat_faildump_path] => /data/moodle/behat_v31screendump
    [dirroot] => /data/apache/moodle-vhosts/v31-0802
    [filepermissions] => 438
    [umaskpermissions] => 0
    [behatrunprocess] => 
    [libdir] => /data/apache/moodle-vhosts/v31-0802/lib
    [tempdir] => /data/moodledata/temp
    [cachedir] => /data/moodledata/cache
    [localcachedir] => /data/moodledata/localcache
    [langotherroot] => /data/moodledata/lang
    [langlocalroot] => /data/moodledata/lang
    [yui2version] => 2.9.0
    [yui3version] => 3.17.2
    [yuipatchlevel] => 0
    [disableupdateautodeploy] => 1
)

